language: node_js
node_js:
  - node
env:
  - SERVER_IP_ADDRESS=martinheinz.dev

before_install:
- openssl aes-256-cbc -K $encrypted_fa31ae4837d9_key -iv $encrypted_fa31ae4837d9_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key

after_success:
  - ./src/deploy.sh $SERVER_IP_ADDRESS
