version: '3.7'
services:
  frontend:
    image: martinheinz/blog_frontend:latest
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 80:80
      - 443:443
    environment:
      PROD: ${PROD}
      NGINX_HOST: ${NGINX_HOST}
      API_URL: ${API_URL}
    volumes:
      - /root/setup/data/certbot/conf:/etc/letsencrypt
      - /root/setup/data/certbot/www:/var/www/certbot
      - /root/blog/prod/rss.xml:/home/rss.xml

  backend:
    image: martinheinz/blog_backend:latest
    container_name: backend
    depends_on:
      - blog_db
    ports:
      - 1234:1234
    volumes:
      - /root/setup/data/certbot/conf/live/${API_URL}:/etc/certs

  blog_db:
    image: martinheinz/blog_db:latest
    container_name: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      DB_NAME: "blog"
      POSTGRES_DB: blog
      PGPORT: 5432
      POPULATE_DB: ${POPULATE_DB}

volumes:
  data: {}
